cabal-version:      3.4
name:               wooden-puzzle-parallel
version:            0.1.0.0
synopsis:           Running the woodn puzzle parallel
license:            GPL-3.0-only
license-file:       LICENSE
author:             Michael Dressel
maintainer:         michael.dressel@kloenplatz.de
category:           Game
build-type:         Simple
extra-doc-files:    README.md

common configs
    build-depends:      base , linear , time, regex-tdfa 
    ghc-options:        -Wall -threaded -O2
    hs-source-dirs:   src/
    default-language: Haskell2010

library
    import:              configs
    exposed-modules:     WPmodule, StaticPieces, Fltr

executable wooden-puzzle-parallel
    import:           configs
    other-modules:    WPmodule, StaticPieces, Fltr
    main-is:          wooden_puzzle_parallel.hs
    ghc-options:        -Wall -O2 -threaded -with-rtsopts=-N

executable comp
    import:           configs
    other-modules:    WPmodule, StaticPieces, Fltr
    main-is:          compWoodenPuzzle.hs
    ghc-options:        -Wall -threaded -with-rtsopts=-N

executable static-pieces
    import:           configs
    other-modules:    WPmodule, StaticPieces, Fltr
    main-is:          StaticPiecesMain.hs
    ghc-options:        -Wall

